#!/usr/bin/env python3
"""Generate sitemap.xml with a real lastmod per page.

A hand-written lastmod goes stale the moment someone forgets to bump it, and a
stale date is worse than none — it tells search engines not to bother
recrawling. Each URL's date therefore comes from the last commit that touched
the file behind it.

    python tools/build-sitemap.py

Runs automatically in the deploy workflow, so the dates are always correct on
the published site.
"""

import io
import os
import subprocess
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = 'https://kairo1980.de'

# url path -> (files whose changes count as a change to this page, priority,
#              changefreq)
PAGES = [
    ('/',                ['index.html', 'config.js', 'zones.js', 'order.js', 'style.css'], '1.0', 'weekly'),
    # The corporate offer is rendered from the same config and zone data as the
    # ordering page, so a changed threshold or a new postcode changes this page
    # too — even though its own markup was not touched.
    ('/firmencatering',  ['firmencatering.html', 'config.js', 'zones.js', 'order.js'], '0.8', 'monthly'),
    ('/impressum',       ['impressum.html'],  '0.2', 'yearly'),
    ('/datenschutz',     ['datenschutz.html'], '0.2', 'yearly'),
]


def last_commit_date(paths):
    """Newest commit date across the given files, or today if git is unusable."""
    newest = None
    for path in paths:
        if not os.path.exists(os.path.join(ROOT, path)):
            continue
        try:
            out = subprocess.check_output(
                ['git', 'log', '-1', '--format=%cs', '--', path],
                cwd=ROOT, stderr=subprocess.DEVNULL).decode().strip()
        except (subprocess.CalledProcessError, OSError):
            continue
        if out and (newest is None or out > newest):
            newest = out
    return newest or date.today().isoformat()


def main():
    entries = []
    for loc, paths, priority, freq in PAGES:
        entries.append(
            '  <url>\n'
            '    <loc>%s%s</loc>\n'
            '    <lastmod>%s</lastmod>\n'
            '    <changefreq>%s</changefreq>\n'
            '    <priority>%s</priority>\n'
            '  </url>' % (BASE, loc, last_commit_date(paths), freq, priority))

    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Generated by tools/build-sitemap.py. Do not edit by hand. -->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + '\n'.join(entries) + '\n</urlset>\n')

    io.open(os.path.join(ROOT, 'sitemap.xml'), 'w',
            encoding='utf-8', newline='\n').write(xml)
    print('sitemap.xml written — %d urls' % len(entries))
    for loc, paths, _, _ in PAGES:
        print('  %-14s %s' % (loc, last_commit_date(paths)))


if __name__ == '__main__':
    main()
